name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    strategy:
      matrix:
        # add any other Typst versions that your package should support
        typst-version: ["0.12"]
        # the docs don't need to build with all versions supported by the package;
        # the latest one is enough
        include:
          - typst-version: "0.12"
            doc: 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Probe runner package cache
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: cargo
          version: 1.0

      - name: Install just from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: just

      - name: Setup typst
        id: setup-typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: ${{ matrix.typst-version }}

      - name: Run test suite
        run: just test

      - name: Build docs
        if: ${{ matrix.doc }}
        run: just doc
